version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - python-app

  python-app:
    build:
      context: ./Python
    container_name: python_app
    expose:
      - "8000"
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge